version: '2'

services:
  nodejs:
    build: ./nodejs-selfhost
    container_name: api-benchmark-nodejs
    ports:
      - "8110:8110"
  aspnetcore-mvc:
    build: ./aspnetcore-mvc-selfhost
    container_name: api-benchmark-aspnetcore-mvc
    ports:
      - "8105:8105"
