version: '2'

services:
  nodejs:
    build: ./nodejs
    container_name: api-benchmark-nodejs
    ports:
      - "8110:8110"
  aspnetcore-mvc:
    build: ./aspnetcore-mvc
    container_name: api-benchmark-aspnetcore-mvc
    ports:
      - "8105:8105"
  aspnetcore-http:
    build: ./aspnetcore-http
    container_name: api-benchmark-aspnetcore-http
    ports:
      - "8120:8120"
  mono-owin:
    build: ./mono-owin
    container_name: api-benchmark-mono-owin
    ports:
      - "8130:8130"
  mono-nancy:
    build: ./mono-nancy
    container_name: api-benchmark-mono-nancy
    ports:
      - "8140:8140"
